### ISSUE TITLE
import 方式

### ISSUE THREAD

**Issue by madneal** [MiSecurity/x-patrol#1]
go 新手，最近把这个项目导入到goland 里面，发觉有一些引入，比如 models.go 里面
```go
import (
	"x-patrol/settings"
	"x-patrol/logger"
)
```

IDE 提示无法引入，改为相对路径 ../settings 就没有问题，这样是正常的么，还是我哪里设置的不正确。

**Comment by netxfly** [comment]
应该是路径与我开发时的不同，改为`$GOPATH/src/x-patrol`时应该没问题。
