### ISSUE TITLE
program can't run success

### ISSUE THREAD

**Issue by alvinyeats** [MiSecurity/x-patrol#14]
When I download this program:
cd x-patrol, then I execute "go build main.go"，I got the following errors:
```
main.go:29:2: cannot find package "github.com/urfave/cli" in any of:
	/usr/lib/golang/src/github.com/urfave/cli (from $GOROOT)
	/root/go/src/github.com/urfave/cli (from $GOPATH)
main.go:28:2: cannot find package "x-patrol/cmd" in any of:
	/usr/lib/golang/src/x-patrol/cmd (from $GOROOT)
	/root/go/src/x-patrol/cmd (from $GOPATH)
```
I think you maybe forget to write some packages that need to depend on, and the package path may be have some problem,
Please update the readme, describe the install&run part clearly, then more newbies can run you program easily.

**Comment by netxfly** [comment]
把项目放到$GOPATH下，然后利用`go get `安装缺少的依赖包，如：
```
go get github.com/urfave/cli
```
