### ISSUE TITLE
error while running go-get

### ISSUE THREAD

**Issue by 0xaud** [MiSecurity/x-patrol#20]
Running go-get  results in

`root@bugdiscloseguy:~# go get github.com/MiSecurity/x-patrol
package x-patrol/cmd: unrecognized import path "x-patrol/cmd" (import path does not begin with hostname)`

**Comment by netxfly** [comment]
这种是仓库自有的，不用go get，先设置好GOPATH，然后mkdir -p $GOPATH/src，把代码放到src目录下就可以了
