### ISSUE TITLE
scan功能一直提示空指针，go语言不知道怎么修改，求大佬指点

### ISSUE THREAD

**Issue by Baibing0118** [MiSecurity/x-patrol#25]
<img width="978" alt="1" src="https://user-images.githubusercontent.com/32734962/53299114-66488780-3871-11e9-9fbf-6086e0bd7110.png">
<img width="716" alt="2" src="https://user-images.githubusercontent.com/32734962/53299117-66488780-3871-11e9-84c1-a8d8fbb035dd.png">

**Comment by netxfly** [comment]
没有配置github的token，在web中配置了就可以用了。
