### ISSUE TITLE
功能咨询

### ISSUE THREAD

**Issue by Baibing0118** [MiSecurity/x-patrol#26]
大神好，
        想问下大神，咱们的源码监控目前是否实现 **增量扫描以及邮件通知功能**，感谢大神回复。真心感谢大神无私的指点！

**Comment by netxfly** [comment]
增量扫描是指不重复插入扫描结果吧？目前就是这样的，重复的结果不会再入库了。
邮件通知的功能也可以加，回头我抽空加一下。

**Comment by Baibing0118** [comment]
大神好、
        感谢大神回复！我最近也在学习这方面的知识！想为项目助力、可惜能力有限、所以不断向大神提问！
         邮件提醒功能感觉真的重要
         另外想跟大神咨询下，是不是第一次扫描完成、在扫描结果中需要一一确认，选择忽略或者是确认。后续每次扫描的话，就不会再扫描出已经选择过的敏感信息代码了？另外就是如果多个关键字查询，是否也能完美兼容？想跟大神确认了解下，实在感谢！
        


在2019年02月27日 14:21，netxfly 写道：

增量扫描是指不重复插入扫描结果吧？
邮件通知的功能也可以加，回头我抽空加一下。

**Comment by netxfly** [comment]
是的，目前的机制就是需要在结果中确认，之后不会再重复记录。
关于关键字，因为直接调用的是github的api，语法可以参考github的文档，https://help.github.com/en/articles/searching-code#considerations-for-code-search

不同的关键字不能写成一个，只能分成2条记录写。

**Comment by Baibing0118** [comment]
收到！感谢大神悉心回复指点！


在2019年02月27日 15:59，netxfly 写道：

是的，目前的机制就是需要在结果中确认，之后不会再重复记录。
关于关键字，因为直接调用的是github的api，语法可以参考github的文档，https://help.github.com/en/articles/searching-code#considerations-for-code-search

不同的关键字不能写成一个，只能分成2条记录写。
