### ISSUE TITLE
安装go

### ISSUE THREAD

**Issue by Tren** [MiSecurity/x-patrol#6]
还是不行 我在服务器上安装 用源码安装
![1521468636 1](https://user-images.githubusercontent.com/20461924/37600578-b352b9ea-2bc2-11e8-9781-2909e2a0d510.png)
![1521468666 1](https://user-images.githubusercontent.com/20461924/37600583-b3d902d4-2bc2-11e8-8956-c09e672920ef.png)

**Comment by netxfly** [comment]
缺少依赖包，程序报的那个`can't find package xxxx`处是缺少的依赖包，逐个go get 回来就可以了。例如：
```
go get github.com/urfave/cli
```
