### ISSUE TITLE
-bash: ./main: No such file or directory

### ISSUE THREAD

**Issue by nmshuishui** [MiSecurity/x-patrol#8]
ubuntu 14.04，使用 ./main web启动的时候报下面错误
![111](https://user-images.githubusercontent.com/8190352/38462171-9afb8906-3b14-11e8-8b18-29efb838b996.jpg)

**Comment by netxfly** [comment]
只下了源码，还没有编译出可执行文件来？

**Comment by nmshuishui** [comment]
刚搞定GOPATH，现在编译报这样，导入不了那个包
![111](https://user-images.githubusercontent.com/8190352/38462786-23e86bc6-3b1f-11e8-9cb2-abe0df674b12.jpg)

**Comment by netxfly** [comment]
需要先go get 一下缺少的包，比如：
```
go get github.com/urfave/cli
```
通过上面的报错来看，gopath应该也没设置好。
可以先看看谢大的go教程的第一章，https://github.com/astaxie/build-web-application-with-golang/blob/master/zh/preface.md
