### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nmshuishui** [MiSecurity/x-patrol#9]
`go version go1.10.1 linux/amd64`
`./main scan`
报错：
![111](https://user-images.githubusercontent.com/8190352/38484272-998f5fe4-3c08-11e8-9ad6-d1c465c247bb.jpg)

**Comment by netxfly** [comment]
应该是github token不正确？

我在看`https://github.com/MiSecurity/x-patrol/blob/master/util/githubsearch/gitclient.go`79行的代码时是一个break，你那边是`return c, c.Token, err`这行报错？
```go
func GetGithubClient() (*Client, string, error) {
	var c *Client
	clients, err := InitGithubClients()
	for _, client := range clients {
		c = client
		break
	}
	return c, c.Token, err
}
```

**Comment by nmshuishui** [comment]
谢谢，是github token的问题，我把生成的token添加到web里的token管理里，现在执行`./main scan` 不报错了
